# If you need to 'vendor your gems' for deploying your daemons, bundler is a
# great option. Update this Gemfile with any additional dependencies and run
# 'bundle install' to get them all installed. Daemon-kit's capistrano
# deployment will ensure that the bundle required by your daemon is properly
# installed.
#
# For more information on bundler, please visit http://gembundler.com

source 'https://rubygems.org'

# daemon-kit
gem 'daemon-kit'

gem 'aws-sdk'
gem 'faraday'
gem 'json'
gem 'safely'

group :development, :test do
  gem 'rake'
  gem 'rspec' 
end
